name: Build/Test

on:
  push:
    branches:
      - "prerelease"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Initialize environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.8.0

      - name: Install dependencies
        run: yarn

      - name: Build scripts
        run: yarn build

      - name: Run tests
        run: yarn test --forceExit