name: Build/Test

on:
  push:
    branches:
      - "prerelease"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Initialize environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.8.0

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test --forceExit
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}